name: Build

on: [push, workflow_call]

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules
  CACHED_BUILD_PATHS: ${{ github.workspace }}/dist
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  dependency_cache:
    uses: sharlottes/judgekit/.github/workflows/dependency_cache.yml@master
  test:
    uses: sharlottes/judgekit/.github/workflows/test.yml@master

  build:
    runs-on: ubuntu-latest
    needs: [dependency_cache, test]
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: SetUp Node.js 16v
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Check dependency cache
        uses: actions/cache@v2
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js Packages when no packages cache
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: yarn
        
      - name: Check build cache
        uses: actions/cache@v2
        id: cache_built_packages
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ runner.os }}-node-${{ env.BUILD_CACHE_KEY }}

      - name: Build when no build cache
        if: steps.cache_built_packages.outputs.cache-hit == ''
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built package
          path: ${{ env.CACHED_BUILD_PATHS }}
