name: Build

on: [push, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Environment
        uses: sharlottes/judgekit/.github/workflows/setup.yml

      - name: Build
        run: yarn && yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built package
          path: dist
