name: Setup

on: workflow_call

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules

jobs:
  dependency_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: SetUp Node.js 16v
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Cache Node.js Dependency Packages
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js Packages when no packages cache
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: yarn
