name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    uses: sharlottes/judgekit/.github/workflows/build.yml@master

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: SetUp Node.js 16v
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Download built package
        uses: actions/download-artifact@v3
        with:
          name: built package

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check NPM Info
        run: npm info judge-toolkit
