name: Publish to NPM

on: release

jobs:
  publish-npm:
    uses: sharlottes/judgekit/.github/workflows/build.yml@main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check NPM Info
        run: npm info judge-toolkit
