name: Node.js Package

on:
  push: 
    branches:
      - master
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Publish to NPM
        run: npm publish
          
      - name: Check NPM
        run: npm info judge-toolkit
        
  publich-gpr:
      runs-on: ubuntu-latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 16.x
          uses: actions/setup-node@v3
          with:
            registry-url: 'https://npm.pkg.github.com'
            
        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build
        
        - name: Publish to GPR
          run: npm publish

