name: Publish to NPM

on: release

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup.yml

      - name: Download built package
        uses: actions/download-artifact@v3
        with:
          name: built package

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check NPM Info
        run: npm info judge-toolkit
