name: Test

on: workflow_call

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules
  
jobs:
  dependency_cache:
    uses: sharlottes/judgekit/.github/workflows/dependency_cache.yml@master

  test:
    runs-on: ubuntu-latest
    needs: dependency_cache
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: SetUp Node.js 16v
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Cache Node.js Dependency Packages
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Test by Jest
        run: yarn test

      - name: Archive jest code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/lcov-report
